import Head from "next/head";
import Link from "next/link";
import { type PostHog } from "posthog-js";
declare const posthog: PostHog;
import { createToast } from "vercel-toast";

export default function FAQs() {

    const captureTestEvent = () => {
        posthog.capture("test-event")
        createToast("posthog.capture('test-event')", {
            timeout: 3000
        });
    }

    return (
        <>
            <Head>
                <title>FAQs</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        FAQs
                    </h1>
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href="/"
                        >
                            <h3 className="text-2xl font-bold">Home →</h3>
                            <div className="text-lg">
                                Just the basics - Everything you need to know to set up your
                                database and authentication.
                            </div>
                        </Link>
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href="/pricing"
                        >
                            <h3 className="text-2xl font-bold">Pricing →</h3>
                            <div className="text-lg">
                                Learn more about Create T3 App, the libraries it uses, and how
                                to deploy it.
                            </div>
                        </Link>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                        <button
                            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                            onClick={captureTestEvent}
                        >
                            capture test event
                        </button>
                    </div>
                </div>
            </main>
        </>
    );
}
